AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
